### PR TITLE
add ability to include title and subtitles for single albums (taken from picasa)

### PR DESCRIPTION
**Pull request by mkoryak**
add ability to include title and subtitles for single albums (taken from picasa),
also use html5 data attributes to always override options, remove metadata plugin use.

### CODE REVIEW

**Comment by oetiker** [comment]
could you make your patch so, that it only adds the new feature, by changing every other line, it makes it a bit difficult to see what you are doing ...

**Comment by mkoryak** [comment]
yeah, i shouldn't have reformatted the entire file. I have removed that now. Let me know what you think. Feel free to rename the options i added, those aren't the best names but i couldn't think of anything better at the time.

**Comment by mkoryak** [comment]
on an unrelated note, your plugin is awesome. Thank you for making it. I am using it here:

http://thetraditionalhunter.com/Muzzle-Loading-Firearms.htm

**Comment by oetiker** [comment]
looking at the diff, it seems there is still a ton of reformatting going on in jquery.EmbedPicasaGallery.js, hiding the intent of your changes ...

**Comment by mkoryak** [comment]
bah, you are right. my editor is doing something evil to white space. ill try to figure out how make it stop

**Pull request closed without merging**
